---
title: "Linear Regression Applications"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{multirow}
   - \usepackage{multicol}
   - \usepackage{changepage}
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\E}{\mbox{E}}
\newcommand{\Var}{\mbox{Var}}
\newcommand{\Cov}{\mbox{Cov}}
\newcommand{\Prob}{\mbox{P}}
\newcommand*\diff{\mathop{}\!\mathrm{d}}

# Exercises


\indent 1. HFI   

Choose another freedom variable and a variable you think would strongly correlate with it. The `openintro` package contains the data set `hfi`. Type `?openintro::hfi` in the Console window in RStudio to learn more about the variables. 
    
a. Produce a scatterplot of the two variables.
b. Quantify the strength of the relationship with the correlation coefficient.
c. Fit a linear model. At a glance, does there seem to be a linear relationship?
d. How does this relationship compare to the relationship between `pf_expression_control` and `pf_score`? Use the $R^2$ values from the two model summaries to compare. Does your independent variable seem to predict your dependent one better? Why or why not?
e. Display the model diagnostics for the regression model analyzing this relationship.
f. Predict the response from your explanatory variable for a value between the median and third quartile. Is this an overestimate or an underestimate, and by how much? In other words, what is the residual for this prediction?
