---
title: "Lesson 35 Application Solutions"
author: "Lt Col Ken Horton"
date: "November 18, 2019"
header-includes: 
  - \usepackage{amsmath,multirow}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align='center')
knitr::opts_chunk$set(out.width = "75%")
```


\newcommand{\E}{\mbox{E}}
\newcommand{\Var}{\mbox{Var}}
\newcommand{\Cov}{\mbox{Cov}}
\newcommand{\Prob}{\mbox{P}}
\newcommand*\diff{\mathop{}\!\mathrm{d}}

# Exercises

\indent 1. The `poisons.csv` dataset contains results of an experiment evaluating survival times of animals exposed to certain types of poisons and certain types of treatments.

a) Build a set of three boxplots that summarize survival time by type of poison. Describe the relationship you see. HINT: You may need to convert the `poison` variable to a factor prior to continuing. 


b) Build a linear model fitting survival time against type of poison. Does there appear to be a significant difference in mean survival time by type of poison? 


c) Write out the estimated linear model. In words, interpret the coefficient estimates. 


d) Obtain pairwise differences to determine where the significant differences lie. 


