---
title: "Lesson 23 Applications"
author: "Name"
date: "Date"
header-includes: 
  - \usepackage{amsmath,multirow}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align='center')
knitr::opts_chunk$set(out.width = "75%")
```


\newcommand{\E}{\mbox{E}}
\newcommand{\Var}{\mbox{Var}}
\newcommand{\Cov}{\mbox{Cov}}
\newcommand{\Prob}{\mbox{P}}
\newcommand*\diff{\mathop{}\!\mathrm{d}}

# Exercises

\indent 1. Suppose we roll a fair six-sided die and let $X$ be the resulting number. The distribution of $X$ is discrete uniform. (Each of the six discrete outcomes is equally likely.) 

a) Suppose we roll the fair die 5 times and record the value of $\bar{X}$, the *mean* of the resulting rolls. Under the central limit theorem, what should be the distribution of $\bar{X}$? 



b) Simulate this process in `R`. Plot the resulting empirical distribution of $\bar{X}$ and report the mean and standard deviation of $\bar{X}$. Was it what you expected? 

(HINT: You can simulate a die roll using the `sample` function. Be careful and make sure you use it properly.) 



c) Repeat parts a) and b) for $n=20$ and $n=50$. Describe what you notice. Make sure all three histograms are plotted on the same $x$-axis scale. 


&nbsp;

\indent 2. Consider Example 23.1 from the narrative. For the moment, assume the population mean ($\mu$) is 67 inches. 

a) What is the distribution of ${\bar{X}-\mu\over S/\sqrt{n}}$ (the $t$-statistic)? 


b) You have collected a random sample of 50 student heights. The sample mean turned out to be $\bar{x}=68.7$ and the sample standard deviation was $s=5.3$. Compute the value of the $t$-statistic for this specific sample. 


c) We assumed the population mean height is 67 inches; however, simply by chance, our sample mean height was 68.7 inches, which is inconsistent with the population mean. In fact, it is unlikely that we would obtain a sample mean of exactly 67 inches even if the true mean height is 67 inches. What is the probability of obtaining the sample described in part (b)? Specifically, what is the probability we obtained the $t$-statistic in part (b), or further away from 0? 


(d) Based on your answer of part (c), could 67 inches be a feasible value for the population mean student height? 



&nbsp;

\indent 3. Exploration of the chi-squared and $t$ distributions. 

a) In `R`, plot the pdf of a random variable with the chi-squared distribution with 1 degree of freedom. On the same plot, include the pdfs with degrees of freedom of 5, 10 and 50. Describe how the behavior of the pdf changes with increasing degrees of freedom. 



b) Repeat part (a) with the $t$ distribution. Add the pdf of a standard normal random variable as well. What do you notice? 


&nbsp;

\indent 4. In this lesson, we have used the expression *degrees of freedom* a lot. What does this expression mean? When we have sample of size $n$, why are there $n-1$ degrees of freedom? Give a short concise answer (about one paragraph). You will likely have to do a little research on your own. 

